apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-mig-parted-config
  namespace: gpu-operator
data:
  config.yaml: |
    version: v1
    mig-configs:
      profile-0-2-1-0-0:
        - devices: [1]
          mig-enabled: true
          mig-devices:
            "2g.10gb": 2
            "3g.20gb": 1
      profile-1-3-0-0-0:
        - devices: [1]
          mig-enabled: true
          mig-devices:
            "1g.5gb": 1
            "2g.10gb": 3
      all-disabled:
        - devices: [0,1,2,3]
          mig-enabled: false
      all-enabled:
      - devices: [0,1,2,3]
        mig-enabled: true
        mig-devices: {}