apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconfig
  namespace: gpu-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: reconfig
  template:
    metadata:
      labels:
        name: reconfig
    spec:
      serviceAccountName: kubecomp
      containers:
      - name: reconfig
        image: "mig-reconfig-mgr:local"
        volumeMounts:
        - name: mig-config-volume
          mountPath: /etc/config
      volumes:
        - name: mig-config-volume
          configMap:
            name: custom-mig-parted-config
       