apiVersion: v1
kind: Pod
metadata:
  name: reconfig
  namespace: gpu-operator
spec:
  restartPolicy: Always
  serviceAccountName: kubecomp
  containers:
  - name: reconfig
    image: "mig-reconfig-mgr:local"
    volumeMounts:
    - name: mig-config-volume
      mountPath: /etc/config
    - name: device-plugin
      mountPath: /var/lib/kubelet/pod-resources/kubelet.sock
  volumes:
    - name: mig-config-volume
      configMap:
        name: custom-mig-parted-config
    - name: device-plugin
      hostPath:
        path: /var/lib/kubelet/pod-resources/kubelet.sock
      